
wavefront:
  container_name: wavefront
  ports:
    - "3878:3878"
    - "2878:2878"
    - "4242:4242"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  image: ezeev/wavefront
  hostname: evan.macbook.dockerhost

dockerui:
  container_name: dockui
  ports:
    - "9000:9000"
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  image: dockerui/dockerui

statsd:
  container_name: statsd
  ports:
    - "8125:8125/udp"
  volumes:
    - ../statsd/config.js:/opt/statsd/config.js
  image: wavefronthq/statsd

web01:
  container_name: web01
  ports:
   - "81:80"
  volumes:
   - ../web:/usr/share/nginx/html
   - ../nginx/nginx.conf:/etc/nginx/nginx.conf
  image: nginx
  
web02:
  container_name: web02
  ports:
   - "82:80"
  volumes:
   - ../web:/usr/share/nginx/html
   - ../nginx/nginx.conf:/etc/nginx/nginx.conf
  image: nginx

haproxy:
  container_name: haproxy
  ports:
   - "90:90"
   - "80:80"
   - "9983:9983"
  links:
    - web01
    - web02
    - solr1
    - solr2
  volumes:
    - ../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  image: haproxy:1.5

ambassador:
    container_name: ambassador
    image: cpuguy83/docker-grand-ambassador
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    command: "-name zoo1 -name zoo2 -name zoo3"

zoo1:
  image: ezeev/zookeeper
  container_name: zoo1
  ports:
   - "2181:2181"
   - "2888:2888"
   - "3888:3888"
  volumes:
   - ../zookeeper/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
   - ../zookeeper/myid.1:/var/lib/zookeeper/myid
   
zoo2:
  image: ezeev/zookeeper
  container_name: zoo2
  ports:
   - "2182:2181"
   - "2889:2888"
   - "3889:3888"
  volumes:
   - ../zookeeper/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
   - ../zookeeper/myid.2:/var/lib/zookeeper/myid
   
zoo3:
  image: ezeev/zookeeper
  container_name: zoo3
  ports:
   - "2183:2181"
   - "2890:2888"
   - "3890:3888"
  volumes:
   - ../zookeeper/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
   - ../zookeeper/myid.3:/var/lib/zookeeper/myid   

solr1:
  image: ezeev/solr
  container_name: solr1
  links:
    - zoo1
    - zoo2
    - zoo3
  ports:
    - "8983:8983"
  command: bin/solr -f -c -z "zoo1:2181,zoo2:2181,zoo3:2181"
  
solr2:
  image: ezeev/solr
  container_name: solr2
  links:
    - zoo1
    - zoo2
    - zoo3
  ports:
    - "8984:8983"
  command: bin/solr -f -c -z "zoo1:2181,zoo2:2181,zoo3:2181"
  
  
